FROM httpd:2.4-alpine
# Copie la page d'accueil dans le dossier servi par Apache
#COPY index.html /usr/local/apache2/htdocs/index.html
# avec conf
COPY index.html /usr/local/apache2/htdocs/index.html
COPY httpd.conf /usr/local/apache2/conf/httpd.conf
