name: CI devops 2025

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ../../backendAPI/simple-api-student-main

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

 
      - name: Build and test with Maven
        run: mvn -B -ntp clean verify

